spring:
  datasource:
    url: jdbc:postgresql://91.107.191.99:5432/env_db
    driver-class-name: org.postgresql.Driver
    username: env_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  freemarker:
    allow-session-override:
  jwt:
    length_expire: 6000000
    length_expire_refresh: 30L*60*10000
  #----------- config file
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB



