server:
  port: 8097
  cors:
    origins:
      - http://91.107.191.99:3000
      - http://localhost:3000
      - http://localhost:3000
      - http://91.107.191.99:3000
      - http://localhost:3001
      - http://91.107.191.99:3001
      - https://qmars.khodaa.de:8443
    methods:
      - POST
      - PUT
      - GET
      - OPTIONS
  servlet:
    context-path: /authentication
spring:
  profiles:
    active: developer
  #    active: operation
  #    active: test
  application:
    name: authentication # current service name used for eureka registration

  devtools:
    add-properties: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


#---- eureka public config
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20 # Notifying Eureka that the client is up or down or killed (second)
    leaseExpirationDurationInSeconds: 20 # Notifying Eureka that the client is up or down or killed (second)
    prefer-ip-address: true # registers the service ip rather than the server name
    hostname: localhost
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8766/eureka # discovery service location

#----------- allowed cors origin
cors:
  allowed-origins:
    - https://qmars.khodaa.de:8443
    - https://91.107.191.99:8443
    - http://91.107.191.99:8096
    - http://localhost:8096
    - http://localhost:3000
    - http://91.107.191.99:3000
    - http://localhost:3001
    - http://91.107.191.99:3001
token:
  number_token: 3

locale:
  default: fa

base_type:
  users: users


