#server:
#  port: 8095
server:
  port: 8095
  ssl:
    key-store: file:./files/sslkeystore/eventManager.p12
#    key-store: file:/root/jarFiles/event/sslkeystore/eventManager.p12
    key-store-password: '123456'
    key-store-type: PKCS12
    key-alias: cleansing
eureka:
  instance:
    prefer-ip-address: true # registers the service ip rather than the server name
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8766/eureka # discovery service location
