server:
  port: 8091
spring:
  datasource:
    url: jdbc:oracle:thin:@172.24.66.69:1521/PDB_DWH
    username: user_mgmt
    password: user_mgmt
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
  freemarker:
    allow-session-override:
  jwt:
    length_expire: 6000000
    length_expire_refresh: 30L*60*10000
  #----------- config file
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  #----------- redis config
  redis:
    host: "172.24.66.76"
    port: 6380
#----------- eureka developer config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # discovery service loc

base_type:
  users: users

#---------- active directory config
ldap:
  job:
    username: job.ldap
    reader:
      enabled: false
      valid_ip:  172.16.11.16
      schedule: "1 * * * * *"

  config:
    server-address: ldap://ldap.shaparak.com
    search-dn: ou=HQ staff,DC=shaparak,DC=local
    domain-name: shaparak.com
    username: IntPortal@shaparak.com
    password: Sh@Parak--2023
